server: 
  port: 8080
spring:
  application:
    name: e-invoice
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

